const fs = require("fs");
const path = require("path");
const { withDangerousMod } = require("expo/config-plugins");

const MARKER = "# withPodsMinDeploymentTarget";

/**
 * Raises the iOS deployment target of every pod target below `minVersion`.
 *
 * Some pods (e.g. RiveRuntime's privacy resource bundle) still declare iOS 14.0,
 * which Xcode 27 rejects ("supported deployment target versions is 15.0 to 27.0").
 * The Podfile is regenerated by `expo prebuild`, so the fix lives in a config plugin.
 */
module.exports = function withPodsMinDeploymentTarget(config, { minVersion = "15.1" } = {}) {
  return withDangerousMod(config, [
    "ios",
    (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, "Podfile");
      const podfile = fs.readFileSync(podfilePath, "utf8");
      if (podfile.includes(MARKER)) return config;

      const hook = "post_install do |installer|\n";
      if (!podfile.includes(hook)) {
        throw new Error("withPodsMinDeploymentTarget: post_install hook not found in Podfile");
      }

      const snippet = [
        `    ${MARKER}`,
        "    installer.pods_project.targets.each do |target|",
        "      target.build_configurations.each do |build_config|",
        "        current = build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']",
        `        if current && Gem::Version.new(current) < Gem::Version.new('${minVersion}')`,
        `          build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${minVersion}'`,
        "        end",
        "      end",
        "    end",
        "",
      ].join("\n");

      fs.writeFileSync(podfilePath, podfile.replace(hook, hook + snippet));
      return config;
    },
  ]);
};
